version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--openssl-legacy-provider
    command: npm run dev

  storybook:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6006:6006"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--openssl-legacy-provider
    command: npm run storybook 