version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3010:3000"
    volumes:
      - .:/app
      - nvl:/app/node_modules
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--openssl-legacy-provider
    command: npm run dev

  prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "3010:80"
    volumes:
      - .:/app
      - nvl:/app/node_modules
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--openssl-legacy-provider
    

  storybook:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6006:6006"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--openssl-legacy-provider
    command: npm run storybook 

volumes:
  nvl:
